name: Checkout
on: push
jobs:
    checkout:
        name: demo
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  submodules: false