name: Checkout
on: push
jobs:
  checkout:
    name: demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: false
      - name: Run Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test Maven
        run: mvn test