name: mvn-test
on: [push]
jobs:
  test-java:
    name: demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: false
      - name: Install java
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Run tests
        run: mvn test

